spring:
  application:
    name: business-service
  profiles:
    include: feign,flyway,orm,redis,tomcat,rest
  flyway:
    table: business_schema_history
  main:
    allow-bean-definition-overriding: true
