spring:
  application:
    name: system-service
  profiles:
    include: feign,flyway,orm,redis,tomcat,rest
  flyway:
    table: system_schema_history
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false