server:
  port: ${arr.tomcat-port}
  tomcat:
    accept-count: 1000
    access-log:
      # 是否关闭接入日志, 这个在运行时线上的时候需要关闭;
      enabled: false
    connection-timeout: 60s
    max-swallow-size: 20MB
    threads:
      max: 200
    mbean-registry:
      enabled: off
  servlet:
    application-display-name: ${spring.application.name}
  #    开启优雅关闭
  shutdown: graceful