spring:
  application:
    name: arr-web
  profiles:
    include: feign,redis,tomcat
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
#      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
#      - com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration
      - org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcClientAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration
  jpa:
    open-in-view: false
