spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apply_room_record_promotion?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB

  mail:
    host: smtp.qq.com
    port: 465
    username: your email
    password: your pwd
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
# 项目配置
arr:
  tomcat-port: ${arr.port.${spring.application.name}}
  host: localhost
  url:
    system-service: ${arr.host}:${arr.port.system-service}
    message-service: ${arr.host}:${arr.port.message-service}
    business-service: ${arr.host}:${arr.port.business-service}
  port:
    system-service: 12010
    message-service: 12011
    business-service: 12012
    arr-web: 12013
arr-web:
  common:
    jwt-secret: 3aa7bc0a-eaee-4649-bd88-32abaa830328
    jwt-expire-time: 1800 # 单位为秒
    jwt-refresh-expire-time: 3600 # 单位为秒

